"""Added meta_json to pdf model

Revision ID: 28b424c7b07e
Revises: 4374234280c4
Create Date: 2025-03-02 20:35:36.943138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28b424c7b07e'
down_revision = '4374234280c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pdf', schema=None) as batch_op:
        batch_op.add_column(sa.Column('document_meta', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pdf', schema=None) as batch_op:
        batch_op.drop_column('document_meta')

    # ### end Alembic commands ###
