"""Added json_meta to conversation model

Revision ID: 96d95dd5d81b
Revises: 28b424c7b07e
Create Date: 2025-03-09 14:42:11.281595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96d95dd5d81b'
down_revision = '28b424c7b07e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('json_metadata', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversation', schema=None) as batch_op:
        batch_op.drop_column('json_metadata')

    # ### end Alembic commands ###
